# Generated by Django 4.1.7 on 2023-10-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video_file',
        ),
    ]
