# Generated by Django 4.1.7 on 2023-10-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_uploaded_at_video_upload_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='file',
        ),
    ]
